name: Lint&Test HelmCharts
on:
  push:
    paths:
      - 'charts/**'
  pull_request:
    paths:
      - 'charts/**'
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch history
        run: git fetch --prune --unshallow
      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: lint --all
      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0
      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: install